pipeline {
    // agent {
    //     dockerfile {
    //         customWorkspace './name-my-pet'
    //         filename 'Dockerfile'
    //     }
    // }
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Build Stage"'
                
                sh 'ls'
                sh 'pwd'
                sh 'docker images'

                // 1. Build image for flask app using Dockerfile
                // dir("name-my-pet") {
                //     sh 'ls'
                //     sh 'pwd'
                //     sh 'docker images'
                //     script {
                //         docker.build('name-my-pet', '-f Dockerfile .')
                //     }
                // }

                sh 'docker images'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Test Stage"'

                // 2. Test docker image/app functionality
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploy Stage"'

                // 3. Run docker image on host machine mapping container port 5000 to host machine port 5000
                // sh 'docker run -d -p 5000:5000 name-my-pet'

                // 3. Push flask app image to Amazon ECR
            }
        }
    }

    post {
        always {
            echo 'The pipeline completed'
        }
        success {
            echo 'Flask Application Up and running!'
        }
        failure {
            echo 'Build failed'
            error('Stopping early...')
        }
    }
}
