apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: namemypet
  name: name-my-pet-clusterip-service
spec:
  ports:
  - name: 8080-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: namemypet
  type: ClusterIP
status:
  loadBalancer: {}