apiVersion: v1
kind: Service
metadata:
  name: name-my-pet-nodeport-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: namemypet
  ports:
    - port: 5000        # port of this service. Cluster members talk via this port
      targetPort: 5000  # where container is actually running
      nodePort: 31479
